language: c
sudo: required
services:
- docker
before_script:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
script: |
	set -ex
	DOCKER_REPOSITORY=torchbox/k8s-ts-ingress
	docker build --pull -t $DOCKER_REPOSITORY:$COMMIT .
	if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
		docker push $DOCKER_REPOSITORY:$COMMIT

		if [ -n "$TRAVIS_TAG" ]; then
			docker tag $DOCKER_REPOSITORY:$COMMIT $DOCKER_REPOSITORY:$TRAVIS_TAG
			docker push $DOCKER_REPOSITORY:$TRAVIS_TAG
		fi
	fi
notifications:
  slack:
    secure: gDQXXz9C5FPFzXJG/5Zpy1AHk0kWvLfkOJSdwTaGrU6jA5zZmcJU46z8pG/ch7qZmTKvtuthdfI5gWd3U8ZFs1KPn3iQwk7LgQgEq3TTBaa+L3DPK9ChD5JnOGiYbTOUYnhwlMRnD/0XxK4gZbJ1aiw2EZmjQRYqYsrKPEYNy3ZGDH9ipHCpBz+83HhlbSOpSq2eeKSjs6+qKeSQZCR7l9u31lWGHWrrzqaDS0/z9Fz0amQXw2bc5me2R1891H6lTZhO1sysVXgXcMfqB2lHetJYyhdbRfLDhpXQD2XvvBbpD139ae40M+1GsnAPMSHnu0vho0I6GTj1lCfomPj2cjzON9hilijMTkDb3DSwwxaB9GORwdH0Y7Cqvj8laihOVC0sCCLUGgEKNPOypB5pNM5h6fnbHsv37iKXhwl7ls76Xf+Fz87v8NnOE4/wPFUga7his6OhtaLJZcDs/s5PAmy8kDQ2WwTlNfX1kqTndHBwzunhW2rrA0IXHujlxS4CCWoKrK5vge0O7jqLvjdMQeP5F1Q8PfTl5mRfu+pgbuOOf66qaGSLM+L43tMOFdq7q0hVi522KRFn30u+521M42szzElfk2uBE4qJwLL8Cz0ByhpoCaZzWYSwJ8R0TVsyknYdHbb96CCreVTcCb9ZJRC+sARJVajA779TJ/6Az6A=
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: AiLedlQfxe6AZoPdLnRzKg9g5QeAWyruzbjBXmJhdaQw2/oF1XZVrHF6hCv8smqAWcCMsNQZg20AssVdOW3V6lsvUx0y3WY69XX4gbH+ekChUME6kcKOsMypazSqo10WnG0S1rAkoDQo6bWaoqSBIs8ZwCyNdN/HOes4eebicGR9X5y6QKKY6x+7+Qmz7XjR4/pfBdynD6aQWXSBR2n30Kox88Jy1gI27o1iJ8wNIvD9IEFrMcwcxFOsOZxWlrPDDZFglfpY29BNQ4Cg9QxRMHH9bDrftuzNHtdOAWvhyNDaOHGvveKg1PBkV37+sneFy2i6MJ3BwKwFvEw+I91vA7qRiXiWxoZRBoKIcSdxhviH0AZP/ulqUk+ImTpc/wwtcW4/2FTK0g02LySWCrjxJm2FUKpIZ8S2aAB+UEpScB5aSd9+kMjEEBI8XeDKmlUTcMn6MG4Hma3wiifUGFPVmlOV10zf1I2H38isue0q8zB+RQpvcGyhgU5MNMR2gmcokM3nxuQSGyroYF/n5xu99u2RuP12oxy/AEMNuxGNCnIj66SnZFXz2aMYmHXaZYY3a3CBL5e782UDQzuUAa3g6VkYIlrsmc5Z2bGVsWodqlk1FE8/mKodDl4Xnze7dmv86en81301rQTSuyV9EyvEaGQK17OOVa8LYh+CI7LqLgU=
  - secure: QiGB4z90HJmM3JfkBuLq8OlAVHz/FFX+rBq6Bafd6I/EqGiHz5QkH4YO1OSbJYAhop1etr1ldzSaJ1uACUcoMun3+9bI6PjMuyrJgn+lsdAXbqs8JXbg2pAFhJux81O+rj/JsxoXZmCBarZJKwYO9rDtrm2OWZZgalYeoxbOudjYuw3/ym2g0l60jzcpJmqRRSJx/QZ5au60x4JHfyaGZZMD9wUcILmD0MNNSzt2CZNrF/H0ebpDOKPxS1EZT4SaWA+VmVWIs4FDWWhSS4/OYVIpn9cjrGwjfFL7pGPt+vFLKdKYeVj7ZPpte4q0iAU/fgSgwls4rpIhoZClsmOXW1GEYiG2Rp/sc2upQD8EWUgetUOsc8sWdijUc+dw8ooLuElXyorWGmCqILq82jz2s66beERc0C3+AlG2ur8CfeqE2rF3N18iDC/g9Xic5zl36ugEU28vK17JY+jLjH/RHMbLJgYIhFECYsnMKbv4fdfZsqOv7r7fNwvNGmfxzh8LeAvVf5QCU0q/UTPtGRTxsTe6EPcjSpwNdHm69KkmRisedtJf7rr2BNBJBSSFlSeWuIVsBoA/bExewiAQb5diq4PeKoVbo4hvSuAy7xMd9bMVkQ+Jg83Xe3HxaAqcQix7E1Tw7NDDrr12w5fYbNv+Ayw5Wc1UZKXOhdmnqphU9mE=
  - secure: D2t0hUjhWSXeUPCwBsU47sGR9EGx9ezgxIZhdhJwpmcM3MA1e3D1+7by64WowtFQzjmXsFCfYvyA3wtbdi0Q0mtbOpyaIlETYhFH9/Uot/3dGmb/ecm4IeQmKtu9qJtdq8ZmQxtwH62Ug/0XDkQOMq8smi2kuap4kSf9q9LaQQd9MbSQJ5IBa2bs0ep3ypaxTUVds2/Oue5YBA1NZQo+dwWcofAj4+hsAWp2onAWnVzx06fJuZyNOul1dZ36+BHa0pOcVC41DdSeG9Z5viNQv7YrD/tgqg8LcadzhaPVusTw/N8kN2WhXvK0nPi3j9Pu4da+uu3KCAms2Wmnab0LeRvZU9FySQoaV/OTl/KWC7W//YskiTr/QfEc/ypzklVHOdCI3UB/B80qGV6pO8r/uow51thEkYDbcpKqbnJGTW5VEcHJq1sAcVek3FyQaiKp2e+xp+EjzGIGmKzA8RPBbLI9nrNjSvQyo6Gd1NY2lECrWljGyj1k4GLmtJUMGYCYWd9kozGIO2go3j/CZQLwB8zN2z8Tk/P4zBfMoDnV8WL4cHJNcGwVe/JOoodWGHdPdes0b9sEFgLJFNxfB3GqJIoLn1I/mtS1S/D6iHgssc8U44M9MxliPTdHUfB+/A7Qbzqrwc/48f++gflIpWDYrU8982/fa4SmrH7U+gpx7U4=
