site_name: TS Ingress Controller
theme: readthedocs
docs_dir: docs
site_dir: _docs
repo_name: GitHub
repo_url: https://github.com/torchbox/k8s-ts-ingress
copyright: Copyright (c) 2016-2017 Torchbox Ltd.
strict: true
pages:
- Home: index.md
- Installation:
  - Installing from source: source.md
  - Using the Docker Image: docker.md
  - Using multiple Ingress controllers: classes.md
  - Configuration: config.md
- Usage:
  - Annotations: annotations.md
  - Caching: caching.md
  - Authentication: auth.md
  - External proxying: external.md
  - TLS: tls.md
